data:
  batch_size: 12
  google_drive_base_path: G:/My Drive/Floral_Detector/Phase1_Foundational-Detector/Phase1_Data/raw_data
  image_size:
  - 224
  - 224
  negative_images_subpath: negative_images (1)
  num_workers: 2
  positive_images_subpath: positive_images
  stratified_splits: true
  test_ratio: 0.15
  train_ratio: 0.7
  val_ratio: 0.15
hard_negative_mining:
  batch_size_inference: 32
  confidence_threshold: 0.9
model:
  architecture: resnet50
  dropout_rate: 0.5
  freeze_backbone_layers: 100
  num_classes: 2
  pretrained: true
reproducibility:
  deterministic: true
  global_random_seed: 42
tensorboard:
  auto_launch: true
  enabled: true
  log_dir: logs/tensorboard
  port: 6006
training:
  device: cpu
  early_stopping:
    min_delta: 0.001
    monitor: val_f1
    patience: 8
  epochs: 50
  learning_rate: 0.0003
  min_recall: 0.85
  optimizer: adam
  production_images_per_class: null
  quick_test_images_per_class: 50
  quick_test_mode: false
  scheduler:
    enabled: true
    factor: 0.5
    min_lr: 1.0e-05
    patience: 5
    type: reduce_on_plateau
  target_precision: 0.98
  weight_decay: 0.0001
