data:
  batch_size: 12
  google_drive_base_path: G:/My Drive/Floral_Detector/Phase1_Foundational-Detector/Phase1_Data/raw_data
  image_size:
  - 224
  - 224
  negative_images_subpath: negative_images (1)
  num_workers: 8
  positive_images_subpath: positive_images
  stratified_splits: true
  test_ratio: 0.15
  train_ratio: 0.7
  val_ratio: 0.15
# Removed unused hard_negative_mining section
model:
  architecture: efficientnet_b0
  dropout_rate: 0.3
  freeze_backbone_layers: 3
  num_classes: 2
  pretrained: true
reproducibility:
  deterministic: true
  global_random_seed: 42
tensorboard:
  auto_launch: true
  enabled: true
  log_dir: logs/tensorboard
  port: 6006
training:
  device: cpu
  early_stopping:
    min_delta: 0.001
    monitor: val_f1
    patience: 8
  epochs: 50
  learning_rate: 0.0001
  min_recall: 0.85
  optimizer: adamw
  production_images_per_class: null
  quick_test_images_per_class: 50
  quick_test_mode: false
  scheduler: cosine_annealing
  min_lr: 1.0e-06
  target_precision: 0.98
  weight_decay: 0.0001
  # Two-stage fine-tuning strategy
  two_stage_training: true
  stage1_epochs: 10  # Freeze backbone, train only classifier
  stage2_learning_rate: 1.0e-05  # Very low LR for fine-tuning
